=== ghillert/jrecruiter/src/test/resources/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (table+)>
<!ELEMENT table (column*, row*)>
<!ATTLIST table
    name CDATA #REQUIRED
>
<!ELEMENT column (#PCDATA)>
<!ELEMENT row (value | null | none)*>
<!ELEMENT value (#PCDATA)>
<!ELEMENT none (#PCDATA)>
<!ELEMENT null EMPTY>

=== ghillert/jrecruiter/src/test/resources/sample-data.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <table name="regions">
        <column>id</column>
        <column>name</column>
        <row><value>-1111</value><value>Other</value></row>
    </table>

    <table name="industries">
        <column>id</column>
        <column>name</column>
        <row><value>-1</value><value>Aerospace</value></row>
        <row><value>-2</value><value>Automotive</value></row>
        <row><value>-3</value><value>Consulting</value></row>
        <row><value>-4</value><value>Energy</value></row>
        <row><value>-5</value><value>IT</value></row>
        <row><value>-6</value><value>Education</value></row>
        <row><value>-7</value><value>Electronics</value></row>
        <row><value>-8</value><value>Financial</value></row>
        <row><value>-9</value><value>Government</value></row>
        <row><value>-10</value><value>Healthcare</value></row>
        <row><value>-11</value><value>Manufacturing</value></row>
        <row><value>-12</value><value>Media</value></row>
        <row><value>-13</value><value>Retail</value></row>
        <row><value>-14</value><value>Telecommunications</value></row>
        <row><value>-15</value><value>Transportation</value></row>
        <row><value>-16</value><value>Other</value></row>
    </table>

    <table name="job_types">
        <column>id</column>
        <column>name</column>
        <row><value>-1</value><value>Full-time</value></row>
        <row><value>-2</value><value>Part-time</value></row>
        <row><value>-3</value><value>Contract</value></row>
    </table>

    <table name="roles">
        <column>id</column>
        <column>name</column>
        <column>description</column>
        <row><value>-1</value><value>ADMIN</value><value>This is the super user of the application</value></row>
        <row><value>-2</value><value>MANAGER</value><value>This role can post new jobs.</value></row>
    </table>

    <table name="users">
    <column>id</column>
    <column>username</column>
    <column>email</column>
    <column>registration_date</column>
    <column>first_name</column>
    <column>last_name</column>
    <column>company</column>
    <column>phone</column>
    <column>fax</column>
    <column>expiration_date</column>
    <column>password</column>
        <row>
            <value>-1</value>
            <value>admin</value>
            <value>admin@jrecuiter.org</value>
            <value>2008-01-10 14:12:00</value>
            <value>ADMIN</value>
            <value>ADMIN</value>
            <value>none</value>
            <value></value>
            <value></value>
            <value>2008-01-10 14:12:00</value>
            <value>aswCoBHvJHtCSyJWRHvch0e4sKflhzkRsP8bUsf1FPTjEkFi3nlQbgtbRx95GluwVr82Ol6WHaLiW/eeoJzXvwjZjEYPgrVYuZmm3Xn0Rek=</value>
        </row>
    </table>

    <table name="user_to_roles">
        <column>id</column>
        <column>users_id</column>
        <column>roles_id</column>
        <row><value>-1</value><value>-1</value><value>-1</value></row>
    </table>

    <table name="configurations">
        <column>message_key</column>
        <column>message_text</column>
        <row><value>mail.from</value><value>a</value></row>
        <row><value>mail.jobposting.body</value><value>b</value></row>
        <row><value>mail.jobposting.email</value><value>n</value></row>
        <row><value>mail.jobposting.subject</value><value>n</value></row>
        <row><value>mail.password.body</value><value>n</value></row>
        <row><value>mail.password.subject</value><value>n</value></row>
    </table>
</dataset>

=== ghillert/jrecruiter/src/db/seed-data.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <table name="regions">
        <column>id</column>
        <column>name</column>
        <row><value>1</value><value>Other</value></row>
        <row><value>2</value><value>Alpharetta</value></row>
        <row><value>3</value><value>Buckhead</value></row>
        <row><value>4</value><value>Decatur</value></row>
        <row><value>5</value><value>Downtown</value></row>
        <row><value>6</value><value>Duluth</value></row>
        <row><value>7</value><value>Marietta</value></row>
        <row><value>8</value><value>Midtown</value></row>
        <row><value>9</value><value>Norcross</value></row>
        <row><value>10</value><value>Perimeter</value></row>
    </table>
    <table name="industries">
        <column>id</column>
        <column>name</column>
        <row><value>1</value><value>Other</value></row>
        <row><value>2</value><value>Engineering</value></row>
        <row><value>3</value><value>Financial</value></row>
        <row><value>4</value><value>Government</value></row>
        <row><value>5</value><value>Healthcare</value></row>
        <row><value>6</value><value>IT</value></row>
        <row><value>7</value><value>Manufacturing</value></row>
        <row><value>8</value><value>Telecommunications</value></row>
    </table>
    <table name="job_types">
        <column>id</column>
        <column>name</column>
        <row><value>1</value><value>Full-time</value></row>
        <row><value>2</value><value>Part-time</value></row>
        <row><value>3</value><value>Contract</value></row>
    </table>
</dataset>
